# Generated by Django 4.2.6 on 2023-11-11 05:40

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=200)),
                ('shop_status', models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ShopSavdo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_count', models.IntegerField(blank=True, null=True)),
                ('serene', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), blank=True, null=True, size=None)),
                ('material', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.BooleanField(blank=True, default=False)),
                ('yaratish', models.BooleanField(blank=True, default=False)),
                ('savdo_count', models.BigIntegerField(blank=True, null=True)),
                ('savdo', models.ManyToManyField(blank=True, to='tutorial.shopsavdo')),
                ('shop_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tutorial.shopname')),
            ],
        ),
    ]
