# Generated by Django 4.2.6 on 2023-11-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0005_alter_arraydjango_serena'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arraydjango',
            name='yosh',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
