# Generated by Django 4.2.6 on 2023-11-07 17:24
from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0006_alter_arraydjango_yosh'),
    ]

    operations = [
        HStoreExtension(),
        migrations.CreateModel(
            name='HistoryField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('data', django.contrib.postgres.fields.hstore.HStoreField()),
            ],
        ),
    ]
