# Generated by Django 4.2.6 on 2023-11-07 17:26

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relation', '0007_historyfield'),
    ]

    operations = [
      
        migrations.RemoveField(
            model_name='historyfield',
            name='data',
        ),
        migrations.AddField(
            model_name='historyfield',
            name='code',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
